### PR TITLE
Added Spotify clients for android

### PR DESCRIPTION
**Pull request by DoYouNotice**
Addtional spotify clients for Android.

xManager: lets you build spotify with additonal features like black Amoled background and ad blocking (Warning this manager has ads which can be turned off) https://github.com/xManager-v2/xManager-Spotify

Blade Player: Open source Spotify client which actually works without Premium. Although they say premium is needed.
missing some features that normal Spotify have. https://github.com/vhaudiquet/BladePlayer

### CODE REVIEW

**Comment by pluja** [comment]
How does xManager help users protect their privacy? Can it remove telemetry from the Spotify app?

**Comment by DoYouNotice** [comment]
It does not remove telemetry, its not actually for privacy but you can compare it to Youtube Vanced. Its build on top of Spotify and gives almost the same experience as when you have Spotify Premium.

**Comment by pluja** [comment]
Could you remove xManager as it seems unclear that it can help with user privacy? On the other hand, Blade Player is good and you can leave it. Once done I'll merge it.

**Comment by DoYouNotice** [comment]
Alright removed xManager, ready to merge.

**Pull request merged**
