### PR TITLE
Add Skiff resources

### PR DESCRIPTION
**Pull request by amilich**
As in the contributing guidelines, I added [Skiff](http://skiff.com/) - end-to-end encrypted mail and collaboration - to the relevant sections with a brief description.

### CODE REVIEW

**Comment by pluja** [comment]
@amilich  Added Skiff mail in f150ef76d213adf974fcbd6da7fcf118ea9308af :)

**Comment by amilich** [comment]
> @amilich Added Skiff mail in [f150ef7](https://github.com/pluja/awesome-privacy/commit/f150ef76d213adf974fcbd6da7fcf118ea9308af) :)

Fantastic!

**Comment by hwyedba4** [comment]
Its privacy policy is problematic

**Comment by pluja** [comment]
@hwyedba4 can you elaborate please? Thank you!

**Pull request merged**
