### PR TITLE
Modifying Smart TV section

### PR DESCRIPTION
**Pull request by ParsaJR**
For the smart TV part, putting software like Kodi is not correct. The operating system is the main issue

### CODE REVIEW

**Comment by Splarkszter** [comment]
So.... you just removed everything and for some reason only added and left LineageOS? FOR TVs???????

**Comment by ParsaJR** [comment]
Yeah . Smart TV is in the operating systems section. So kodi is not for this part. Lineage OS can be installed for some Android boxes.

**Comment by pluja** [comment]
I would like to keep kodi and others, maybe we should create a new section for them?

**Comment by ParsaJR** [comment]
I think you should put them in "Media Streaming Platforms" O_o?

**Pull request closed without merging**
