### PR TITLE
added_bitlocker_to_encryption_avoid

### PR DESCRIPTION
**Pull request by SoftwareRat**
Related to https://github.com/pluja/awesome-privacy/issues/271

### CODE REVIEW

**Comment by cdrnet** [comment]
Yes, BitLocker is a commercial product, Windows-only and fully available only in the more expensive versions. And Microsoft in general is maybe questionable in terms of privacy.

However, how does this affect either privacy or security of **BitLocker** itself?

(Unless maybe you opt-in to upload the keys to your Microsoft account, but this not required at all.)

**Comment by pluja** [comment]
I think that @cdrnet is right. Maybe we should have more reasons to add it to the avoid list. Do we know if such app has any kind of trackers that can gather user data (or metadata) for example?

**Comment by pluja** [comment]
That is a nice explanation. @SoftwareRat could you edit your description to fit the information shared by @monokrome and link to the corresponding comment in this issue?

**Comment by cdrnet** [comment]
> If we need more reason, let's consider that Microsoft has - in the past - gone out of their way to help law enforcement decrypt bitlocker encrypted hard disks without user consent. I recall this being in the news around 15 years ago, maybe? Even if I'm misremembering, Microsoft admittedly stores [disk encryption keys](https://www.vice.com/en/article/bmvjz8/microsoft-disk-encryption-keys-government) which means that they'd be forced by a court to provide the keys if requested. In today's world, warrants for this kind of thing are given out in an automated fashion for NSA projects and similar things.

For completeness maybe also add that this does not seem to be true (anymore) these days, and for many years now. Yes, with BitLocker you can opt-in to upload your recovery keys to a Microsoft Account (not OneDrive), as one way among multiple to recover them if you forget the passphrase. You're not forced to do that and it does not happen automatically without asking (unless it does it anyway, but I'm not aware of any indication it would indeed do that - please correct me on this if you can find any serious infosec report on this aspect). [See here on how this is shown in the UI](https://support.microsoft.com/en-us/windows/back-up-your-bitlocker-recovery-key-e63607b4-77fb-4ad3-8022-d6dc428fbd0d). If you indeed do upload, then you can view and managed them on https://account.microsoft.com/devices/recoverykey - and yes, then of course Microsoft does have direct access to them and could forward them if legally required.

**Comment by cdrnet** [comment]
> There are plenty of reasons to not trust bitlocker in this thread, and probably a thousand more have gone unmentioned. Even ignoring all of this, why recommend it when there are cross-platform open source solutions which already exist?

As stated above I'm not suggesting to actively recommend it, just to not put it into the avoid list - i.e. to not recommend *against* it. It is significantly increasing privacy for a lot of relevant vectors like lost devices or theft (arguable maybe not against government vectors) while being very easy to set up without much risks and downsides. It certainly does not negatively affect your privacy to use BitLocker vs. not using any device encryption.

**Comment by pluja** [comment]
Closing this issue. Will not be adding BitLocker neither recommending it.

**Pull request closed without merging**
