### PR TITLE
Add Read-It-Later (such as Pocket) alternative

### PR DESCRIPTION
**Pull request by rhtenhove**
I was looking for privacy minded alternatives for the popular read it later service Pocket, and was surprised to not find these tools in the list.

So after some searching I came across some privacy-unfriendly services of which Pocket seems to be king. I am not entirely sure about Raindrop.io, but it does seem to be just-another-data-hoarder with a pretty and well phrased privacy policy.

Wallabag was so far the only well designed alternative I could find. If more pop up, I'll add these (or someone else can). It doesn't have fancy (or up to date) phone apps, but it does adhere well to the idea of a privacy focused service which can be accessed by any browser.

### CODE REVIEW

**Comment by rhtenhove** [comment]
Pinboard [appears](https://pinboard.in/privacy/) to have an excellent focus on privacy, but doesn't really have anything to substantiate it other than its word.

Trove also seems to be closed source, and requires Blockstack (or whatever that's called now) to operate, making it even more complex.

So far don't seem to be many alternatives that comply to the requirements of this repo.

**Comment by pluja** [comment]
I am also aware of:

- Shiori - https://github.com/go-shiori/shiori
- LinkAce - https://github.com/Kovah/LinkAce
- LinkDing - https://github.com/sissbruecker/linkding

What about adding them too?

**Comment by pluja** [comment]
As @rhtenhove said, services like trovenow and pinboard seem to be privacy-focused and claim to use encryption, but they do not seem to be verifiable.  Is there any evidence or audit that can certify/prove that they really do what they say?

**Comment by rhtenhove** [comment]
Excellent additions @pluja, thanks!

Trovenow seems to be closed source itself, but relies on the open source blockstacks (and its open source storage engine Gaia) to store everything remotely. It also appears to have a self hosted option. So it could be checked if it tries to connect to anything else other than the self hosted instance. I can't find any audits for it.

Agree on calling them Bookmarks. I'll add Read It Later as a formerly-called to Pocket to make it easier to find.

**Comment by pluja** [comment]
Thank you, @rhtenhove!

@monokrome please start a new Discussion, so we can decide what to do with Trovenow :)

**Pull request merged**
