### PR TITLE
Added Kizie in Twitter section

### PR DESCRIPTION
**Pull request by rishimohan**
[Kizie](https://kizie.co) is a privacy focussed Twitter client which only uses Pirsch for analytics.

### CODE REVIEW

**Comment by pluja** [comment]
Can you explain how is it privacy respecting?

Due to the sorting of the content alphabetically, your PR has n ow conflicts. You can either redo the PR or, if this will be merged, I can add it manually.

**Comment by rishimohan** [comment]
@pluja Hi, here's why Kizie is privacy focussed:

- Kizie only uses Pirsch for analytics(🖤 Pirsch)
- No ads anywhere on the site or third-party service except Stripe and Sentry, so no pixel peeking from any service
- None of user's data is collected except for bare minimum to make the app work
- Protected profiles/tweets are respected and shown only to intended users

I can surely send a new PR if you think Kizie is a right fit in the list 😃, let me know.

**Comment by pluja** [comment]
I see, I will investigate a bit more. Sure, you can make a new PR!

**Comment by rishimohan** [comment]
@pluja Sure, let me know what you think of Kizie :), also I've created new PR to resolve conflicts from this PR here: https://github.com/pluja/awesome-privacy/pull/169

Closing this one.

**Pull request closed without merging**
