### PR TITLE
Add Unidentified Analytics

### PR DESCRIPTION
**Pull request by actuallymentor**
### Unidentified Analytics
* [Unidentified Analytics](https://unidentifiedanalytics.web.app/) - Naive ip-based cross-plafform tracking, useful in websites, shell scripts, and anywhere you can post images or call urls. Source code available at [actuallymentor/unidentified-analytics](https://github.com/actuallymentor/unidentified-analytics)
* **License**: MIT
* **Why do you think this helps users privacy?**: It tracks no personally identifiable data from the person doing the tracking, and the person being tracked.
* **Under what section should this service be listed?**: Analytics
* **Additional comments / info**: I made this tool to track the usage of my moderately popular [mac battery limiting tool](https://github.com/actuallymentor/battery). It's a very convenient way to add "minimum viable tracking" to open source projects. It is very developer friendly, and is unlikely to be useful to commercial players. It's been up and running since feb 2023, though I squashed the dev history today so it looks only today years old on Github.

**Example usage:**

This is a tracking pixel: Privacy friendly user statistics pixel (👈 invisible svg right there)

[And this is where you can see the stats](https://unidentifiedanalytics.web.app/stats/pupil-shut-ourselves-said).

Screenshot of a namespace with data:

Screenshot 2024-04-03 at 12 57 57

### CODE REVIEW

**Comment by pluja** [comment]
Can you explain how you identify unique IPs?

**Comment by actuallymentor** [comment]
Thanks for checking in @pluja! Of course: I rely on the headers of the request. As you can see [on this line of source code](https://github.com/actuallymentor/unidentified-analytics/blob/main/functions/modules/touch.mjs#L11):

```js
 let { ip: request_ip, ips, query: { namespace } } = request
 const ip = request_ip || ips[0] || request.get( 'x-forwarded-for' )
```

This of course limits the granularity of the tracking (ie 5 people on 1 home network are seen as 1 unique ip), but for the purposes of low-stakes tracking it works very well.

**Comment by pluja** [comment]
Are you saving the IPs for tracking? If so, are you saving as is or hashing them?

**Comment by actuallymentor** [comment]
I love that question @pluja, as of now they are stored as hashes. Your question prompted me to change it so no raw ips are stored. See [this merged pull request](https://github.com/actuallymentor/unidentified-analytics/pull/1).

**Comment by pluja** [comment]
awesome! much better that way :)

**Comment by actuallymentor** [comment]
> Merged!

Awesome, thank you :)

> Are you planning any self-hosting options? if so, will it be possible to self-host outside firebase?

I love the idea. Running it DIY on firebase can be done with the code as-is, though I could write some docs on how to do that. Going outside firebase would require a rewrite (or potentially a refactor to be supabase compatible with a docker stack). Currently the only reason I maintain this is to have stats on my [FOSS battery app](https://github.com/actuallymentor/battery). If many other people start using unidentified analytics I'd be up for putting in the refactor effort, but for now it is what it is.

**Pull request merged**
