### PR TITLE
add keyoxide.org

### PR DESCRIPTION
**Pull request by VPraharsha03**
@pluja I think keyoxide.org might be a good link in bio tool and an alternative to tools like LinkTree to share personal link / social media portfolios. Please share your suggestion.

### CODE REVIEW

**Comment by pluja** [comment]
Keyoxide.org looks pretty nice! I don't know if I like the "Link In Bio Tools" title, maybe something like "Link aggregators" would be better? Do you have any other suggestion?

**Comment by VPraharsha03** [comment]
Well, even I thought about "Link aggregators" first. On searching a bit, these tools seem to be popularly called "Link in Bio Tools" on social media.  Maybe something like "Portfolio Sharing Tools"? "Link aggregators" also sounds good.

**Comment by spekulatius** [comment]
It might not hurt to use the common term. More reach is good :)

**Comment by spekulatius** [comment]
It might not hurt to use the common term. More reach is good :)

**Comment by pluja** [comment]
Merging, if we can think of a better title, we'll change it later

**Comment by VPraharsha03** [comment]
> Merging, if we can think of a better title, we'll change it later

Maybe we could rename the section as "Landing Page Services & Tools" ? There's one more open sourced service called [omg.lol](https://home.omg.lol/) (as an example) which offers profile hosting. Keyoxide is much more than a landing page as it offers identity verification as well. It covers one functionality offered by Keybase, which is mapping the social media identities to encryption keys in a publicly auditable manner.

**Comment by pluja** [comment]
Hmm, what about “Social Media Aggregator Tools”?

**Pull request merged**
