### PR TITLE
Add Loggit

### PR DESCRIPTION
**Pull request by BrunoBernardino**
Full disclosure: I'm the author of [Loggit](https://loggit.net).

Loggit is end-to-end encrypted and open source (AGPL-3.0). Additionally, 3.0 is self-hosted. You can read more about [that announcement here](https://loggit.net/blog/announcing-loggit-3.0-self-hostable).

The website also has no analytics or tracking (only page views are counted when loaded).

### CODE REVIEW

**Comment by pluja** [comment]
Maybe it would have a better fit under the "Utilities" category?

**Comment by Splarkszter** [comment]
Thank you so much for making this app! It seems very cool and great, capability of self-hosting is awesome!

Wish the website was more clear about where/how to install/use it. The first thing you see is that you can pay for it, but not that is open-source and that you can self-host it. Someone like me would just click out of it instead of sticking-in and thinking of donating to the project.

**Comment by BrunoBernardino** [comment]
@pluja I'm happy to move it around if you want.

@Splarkszter I'm planning to redo the homepage since it's been like that for a while, and it's had a few new features added since. I'll take that into consideration!

**Comment by pluja** [comment]
@BrunoBernardino please move it under utilitites and I'll merge!

**Comment by BrunoBernardino** [comment]
Done @pluja ! Also @Splarkszter hopefully the new landing page makes it easier to see there's a self-hosting option!

**Comment by Splarkszter** [comment]
> Also @Splarkszter hopefully the new landing page makes it easier to see there's a self-hosting option!

Very well! Thank you so much! The 'Watch Demo' box and the text below are missaligned with the left side but is not an big issue. haha

Thank you for all your efforts everyone!

**Comment by BrunoBernardino** [comment]
> The 'Watch Demo' box and the text below are missaligned with the left side but is not an big issue.

Can you show me a screenshot and tell me what's the browser/OS you're using? I see it well aligned on Firefox and Chrome, Linux.

**Comment by Splarkszter** [comment]
> Can you show me a screenshot and tell me what's the browser/OS you're using? I see it well aligned on Firefox and Chrome, Linux.

Linux Mint - Librewolf [Tho it is on all browsers]



Probably i'm just too picky don't worry.

**Comment by BrunoBernardino** [comment]
Interesting! We're using the same (I'm on Manjaro now, but was on Mint for a long time). The difference seems to be in the installed fonts. I might need to rethink my strategy around them, but I tried to pick fonts that look and feel very similarly, that are generally available across devices, but it seems Ubuntu (I think that's the one triggering for you) uses a bit more. I just tweaked it so it should look fine now, hopefully.

**Pull request merged**
