### PR TITLE
Idea: Added Mega.nz

### PR DESCRIPTION
**Pull request by Kippenhof**

### CODE REVIEW

**Comment by monokrome** [comment]
People are putting confused emojis in reaction to this without detailing their explanation as to why they'd do so, which is generally unhelpful to say the least about it.

Generally, however, it seems like Mega has the **intention** of being secure. Unfortunately, alleged intentions don't mean a lot it seems.

My guess is that, although you decrypt the data in-browser, they  **do** somehow allow you to share files with users without specifically managing your own keys or inviting them. This seems to imply that they keep a copy of all of your data on their end as well as a key to be able to decrypt the data which is also tied to an account which requires you to provide some sort of identifiable information to create. This is a very dangerous trifecta to look out for in general and leans toward potential leaks, government intervention, etc - which have already proven to be an issue thus far with MEGA.

They also seem to request you to manually accept a cookie policy which implies that they track for advertising, performance monitoring, and even third-party services - which is another red flag to me:

Screen Shot 2021-06-09 at 01 47 58

Screen Shot 2021-06-09 at 01 50 10

It is also worth nothing that the mega.nz domain name redirects to mega.io which means they're using a TLD which has been practically unsafe in past occasions and should be considered as a concern as well.

If we add this all together then even though they have the stated intention of caring about user privacy - which means nothing if you consider that Facebook, Google, and others have similar stated intentions - they still don't seem to practice what they preach.

I'd personally say that this project is general not helpful to user privacy but could see people argue otherwise.

**Comment by pluja** [comment]
@monokrome I do use Mega for some personal encrypted backups as I find it a good solution for what I want, I do not keep anything personal there though.

Their clients [are open source](https://github.com/meganz/android) and they encrypt the data on the client. What they are doing serverside is another thing, and this is why I don't want to trust them a lot.

I don't think I will be listing MEGA here anytime soon. But I will keep this open for further discussion.

**Comment by Kippenhof** [comment]
Thx for all the Feedback.

For me was mega the only cloud-provider on which i stored stuff that i am actually using (mostly semi-personal).

I had never an issue with deleted files or leaked information, or just messed up desktop-clients.

I can understand why you won't list mega here, and as far as i said, it was just an idea. I think its an great compromise between good security great usability and big storage capacity (compared to google drive, onedrive dropbox or other commonly used Free Cloud Providers).

**Comment by parcelcat** [comment]
The [Mega sync client](https://github.com/meganz/MEGAsync) isn't open source (according to the [Open Source Definition](https://opensource.org/osd)) since [its license](https://github.com/meganz/MEGAsync/blob/master/LICENCE.md) doesn't allow the use of the source code for anything other than review and commentary. It is source-available, which makes its license better than that of closed source providers like Dropbox, but worse than that of open core alternatives like [Seafile](https://github.com/haiwen/seafile) and open source alternatives like [Nextcloud](https://github.com/nextcloud).

**Comment by Kippenhof** [comment]
I'll just close it

**Pull request closed without merging**
