### PR TITLE
Add ente Auth - Free / Cross Platform / E2EE 2FA app

### PR DESCRIPTION
**Pull request by mnvr**
Hey @pluja. I took the liberty of moving this as the first item in the list, as it is the only one from the list that is cross platform, and it matches (or is better than) the existing entries in all other aspects. But I might be thinking biased (since I'm one of the developers), so please feel free to reorder.

Some mentions/reviews:
- [New oil - Twitter mention](https://twitter.com/thenewoil1/status/1602077944611995649)
- [Detailed review at zeroclick.xyz](https://zeroclick.xyz/ente-auth)
- [FOSS Android - Mastodon review](https://mstdn.social/@foss_android/109505185418700364)

And here is the original blog post introducing it - https://ente.io/blog/auth/

Thank you!

### CODE REVIEW

**Comment by pluja** [comment]
Hey! Thank you for the PR. I'll be happy to add it, but could you please move it below Aegis? I'm trying to keep the list alphabetically sorted so there are no bias!

**Comment by mnvr** [comment]
Done!

**Comment by pluja** [comment]
Merging. Will add a small note that this app needs an ente account to work!

**Comment by mnvr** [comment]
> Merging. Will add a small note that this app needs an ente account to work!

Thank you!

**Pull request merged**
